sudo: false
language: java

jdk:
  - oraclejdk8

script: mvn clean install

before_deploy:
  - export RELEASE_FILE=$(ls target/shipwreck-app-*.war)
  
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file:  $RELEASE_FILE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
